config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :styles

  resources :contents
  get 'admin_pages/main'
  get 'admin_pages/images'
  get 'admin_pages/users'
  get 'admin_pages/startbot'
  get 'admin_pages/startprocess'
  get 'admin_pages/unregworkers'
  get 'admin_pages/update_queue_status'
  match '/admin_pages/update_queue_status', to: 'admin_pages#update_queue_status', via: 'put'
  match '/admin_pages/update_style_status', to: 'admin_pages#update_style_status', via: 'put'
  match '/admin_pages/update_content_status', to: 'admin_pages#update_content_status', via: 'put'
  match '/admin_pages/delete_queue', to: 'admin_pages#delete_queue', via: 'put'

  devise_for :clients, :controllers => { :omniauth_callbacks => "callbacks", :sessions => 'clients/sessions' }
  resources :queue_images
  match '/queue_images/:id/visible', to: 'queue_images#visible', via: 'put'
  match '/queue_images/:id/hidden', to: 'queue_images#hidden', via: 'put'
  match '/queue_images/:id/like', to: 'queue_images#like_image', via: 'put'
  match '/queue_images/:id/unlike', to: 'queue_images#unlike_image', via: 'put'
  get '/queue_images/:id/loaded', to: 'queue_images#loaded'
  post '/queue_images/:id/post_facebook' => 'queue_images#post_facebook', as: :post_facebook_queue_images
  get 'static_pages/lenta', as: 'user_root'
  get '/queue_images/:id/modal' => 'queue_images#show_modal', as: :queue_image_show_modal

  match '/about', to: 'static_pages#about', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/error', to: 'static_pages#error', via: 'get'
  match '/lenta', to: 'static_pages#lenta', via: 'get'
  match '/mixing_level', to: 'static_pages#mixing_level', via: 'get'
  match '/premium', to: 'static_pages#premium', via: 'get'

  resources :blog_posts do
    resources :comments
  end

  resources :comments, only: [:create]

  post '/credits' => 'credits#add', as: :add_credits

  root "static_pages#lenta"
  authenticate :admin do
    mount Resque::Server, :at => "/resque"
  end

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  has_many :comments, as: :commentable

  def short_text
    body.split[0...50].join(' ').html_safe
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_authorize, only: [:edit, :new, :create, :update, :destroy]

  def index
    @blog_posts = BlogPost.order('created_at DESC').all
  end

  def show
    @blog_post = BlogPost.find params[:id]
    @comment = @blog_post.comments.new
    @comments = @blog_post.comments
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new blog_post_params

    if @blog_post.save
      redirect_to blog_posts_path, notice: "The blog post is saved"
    else
      render action: "new", alert: @blog_post.errors.full_messages.to_sentence
    end
  end

  def edit
    @blog_post = BlogPost.find params[:id]
  end

  def update
    @blog_post = BlogPost.find params[:id]
    if @blog_post.update_attributes(blog_post_params)
      redirect_to blog_posts_path, notice: "The blog post is updated."
    else
      render action: "edit", alert: @blog_post.errors.full_messages.to_sentence
    end
  end

  def destroy
    @blog_post = BlogPost.find params[:id]
    @blog_post.destroy
    redirect_to blog_posts_path
  end

  def pundit_user
    current_client
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body)
  end

  def set_authorize
    authorize BlogPost
  end

end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<% if @blog_post.errors.any? %>
  <ul>
    <%= @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @blog_post do |f| %>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
  </div>
  <div>
    <%= f.cktext_area :body, rows: 10 %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2" id="blog">
  <%= "Editing #{@blog_post.title}" %>
  <%= render "form" %>
</div>

app/views/blog_posts/index.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2" id="blog">
  <% if current_client.present? && current_client.admin? %>
    <%= link_to "+ New post", new_blog_post_path, id: 'new-blog-post' %>
  <% end %>
  <% @blog_posts.each do |blog_post| %>
    <div class="blog-post">
      <h3><%= link_to blog_post.title.html_safe, blog_post %></h3>
      <div class="blog-post-body">
        <%= blog_post.short_text %>...
      </div>
      <% if current_client.present? && current_client.admin? %>
        <div class="blog-post-links">
          <%= link_to "Edit", edit_blog_post_path(blog_post) %>
          <%= link_to "Delete", blog_post, method: :delete, class: 'delete-post' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/blog_posts/new.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2" id="blog">
  <h3> New Blog Post</h3>
  <%= render "form" %>
</div>

app/views/blog_posts/show.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2" id="blog">
  <div class="blog-post">
    <h3><%= @blog_post.title.html_safe %></h3>
    <div class="blog-post-body">
      <%= @blog_post.body.html_safe %>
    </div>
    <% if current_client.present? && current_client.admin? %>
      <div class="blog-post-links">
        <%= link_to "Edit", edit_blog_post_path(@blog_post) %>
        <%= link_to "Delete", @blog_post, method: :delete, class: 'delete-post' %>
      </div>
    <% end %>
    <div id="new-comment">
      <div class="row">
        <div class="col-md-6">
          <% if current_client %>
            <%= render partial: 'comments/form', locals: { comment: @comment, remote: false } %>
          <% else %>
            <%= link_to "Sign In", new_client_session_path %>
            or
            <%= link_to "Register", new_client_registration_path %>
            to leave a comment
          <% end %>
        </div>
      </div>
    </div>
    <div id="comments" class="margin-top">
      <%= render partial: 'comments/comment', collection: @comments %>
    </div>
  </div>
</div>