config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :styles

  resources :contents
  get 'admin_pages/main'
  get 'admin_pages/images'
  get 'admin_pages/users'
  get 'admin_pages/startbot'
  get 'admin_pages/startprocess'
  get 'admin_pages/unregworkers'
  get 'admin_pages/update_queue_status'
  match '/admin_pages/update_queue_status', to: 'admin_pages#update_queue_status', via: 'put'
  match '/admin_pages/update_style_status', to: 'admin_pages#update_style_status', via: 'put'
  match '/admin_pages/update_content_status', to: 'admin_pages#update_content_status', via: 'put'
  match '/admin_pages/delete_queue', to: 'admin_pages#delete_queue', via: 'put'

  devise_for :clients, :controllers => { :omniauth_callbacks => "callbacks", :sessions => 'clients/sessions' }
  resources :queue_images
  match '/queue_images/:id/visible', to: 'queue_images#visible', via: 'put'
  match '/queue_images/:id/hidden', to: 'queue_images#hidden', via: 'put'
  match '/queue_images/:id/like', to: 'queue_images#like_image', via: 'put'
  match '/queue_images/:id/unlike', to: 'queue_images#unlike_image', via: 'put'
  get '/queue_images/:id/loaded', to: 'queue_images#loaded'
  post '/queue_images/:id/post_facebook' => 'queue_images#post_facebook', as: :post_facebook_queue_images
  get 'static_pages/lenta', as: 'user_root'
  get '/queue_images/:id/modal' => 'queue_images#show_modal', as: :queue_image_show_modal

  match '/about', to: 'static_pages#about', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/error', to: 'static_pages#error', via: 'get'
  match '/lenta', to: 'static_pages#lenta', via: 'get'
  match '/mixing_level', to: 'static_pages#mixing_level', via: 'get'
  match '/premium', to: 'static_pages#premium', via: 'get'

  resources :blog_posts do
    resources :comments
  end

  resources :comments, only: [:create]

  post '/credits' => 'credits#add', as: :add_credits

  root "static_pages#lenta"
  authenticate :admin do
    mount Resque::Server, :at => "/resque"
  end

end

app/models/admin_page.rb
class AdminPage

end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  include WorkerHelper
  after_action :verify_authorized
  before_action :set_authorize

  def pundit_user
    current_client
  end

  def self.policy_class
    AdminPage
  end


  def main

  end

  def images
    st = params[:status]
    if !st.nil? && st.to_i
      @items= QueueImage.where(status: st.to_i).order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
    else
      @items= QueueImage.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
    end
    @pimage_show = false
    pis = params[:pimage]
    if !pis.nil? && pis == 'true'
      @pimage_show = true
    end
  end

  def users

  end

  def startbot
    start_bot
    redirect_to admin_pages_main_path
    return
  end

  def startprocess
    start_workers
    redirect_to admin_pages_main_path
    return
  end

  def unregworkers
    Resque.workers.each {|w| w.unregister_worker}
    redirect_to admin_pages_main_path
    return
  end

  def update_queue_status
    @queue_image = QueueImage.find(params[:id])
    @queue_image.update(status: params[:status])
    respond_to do |format|
      format.html { redirect_to admin_pages_images_path }
      format.js
    end
  end

  def update_style_status
    @queue_image = QueueImage.find(params[:id])
    @style = @queue_image.style
    @style.update(status: params[:status])
    respond_to do |format|
      format.html { redirect_to admin_pages_images_path }
      format.js
    end
  end

  def delete_queue
    @queue_image = QueueImage.find(params[:id])
    @queue_image.destroy
    respond_to do |format|
      format.html { redirect_to admin_pages_images_path }
      format.js
    end
  end

  def update_content_status
    @queue_image = QueueImage.find(params[:id])
    @content = @queue_image.content
    @content.update(status: params[:status])
    respond_to do |format|
      format.html { redirect_to admin_pages_images_path }
      format.js
    end
  end

  private
  def set_authorize
    authorize AdminPage
  end

end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/views/admin_pages/_item_view_4.html.erb
<% debug = false %>

<%item = item_view_4 %>
<%res_img = item.result_image %>

<div class="row styleRow2-lg">

        <div class="visible-lg  col-lg-2 col-lg-offset-2 userAvatarStyle-lg" >
          <%= link_to(image_tag(item.content.image.thumb200.url, alt:item.content.image, class: "imagesStyle"), item.content.image.url, class: "imagesStyle", data:{ lightbox: "content"}) %>
        </div>
        <div class="visible-lg  col-lg-2 userAvatarStyle-lg">
          <%= link_to(image_tag(item.style.image.thumb200.url, alt:item.style.image, class: "imagesStyle"), item.style.image.url, class: "imagesStyle", data:{ lightbox: "content"}) %>
        </div>


        <div class="hidden-lg col-md-2 col-sm-3 col-xs-3 col-md-offset-2 userAvatarStyle-lg" >
          <%= image_tag(item.content.image.thumb200.url, class: "imagesStyle")%>
        </div>
        <div class="hidden-lg col-md-2 col-sm-3 col-xs-3 userAvatarStyle-lg">
          <%= link_to(image_tag(item.style.image.thumb200.url, alt:item.style.image, class: "imagesStyle"), item.style.image.url, class: "imagesStyle") %>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-3 col-xs-3 userAvatarStyle-lg">
          <div class="visible-lg" >
            <%= link_to(image_tag(res_img.imageurl.thumb400.url, alt:res_img.imageurl, class: "imagesStyle"), res_img.imageurl.url, class: "imagesStyle", data:{ lightbox: "content"})  if res_img %>
          </div>
          <div class="hidden-lg" >
            <%= link_to(image_tag(res_img.imageurl.thumb400.url, alt:res_img.imageurl, class: "imagesStyle"), res_img.imageurl.url, class: "imagesStyle")  if res_img %>
          </div>
        </div>

        <div class=" col-lg-2 col-md-2 col-sm-3 col-xs-3 ">
          <span class="textAboutStyle"><%= item.client.email if !item.client.nil? %></span>
          <span class="textAboutStyle"><%= (item.created_at+10800).strftime("%d.%m.%Y %H:%M:%S")%></span><br>
          <span class="textAboutStyle"><%= "like: #{Like.where(queue_id: item.id).count}" %></span>

          <div id="qi_status_<%= item.id %>">
            <span class="textAboutStyle"><%= get_queue_item_status(item) %></span>
          </div>
          <%= link_to 'SHOW', queue_image_path(item) %><br>
        </div>

</div>

<div class="row">
  <div class=" col-lg-offset-2 col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <%= item.init_str if !item.init_str.blank? %>
  </div>
</div>

<div class="row">
      <div class=" col-lg-offset-1 col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <%= render  partial: 'statuses', :locals => {item: item}  %>
      </div>
</div>

<% if @pimage_show %>
<div class="row">
  <div class="col-lg-offset-2 col-md-offset-2 col-lg-8 col-md-8 col-sm-12 col-xs-12">
  <div class="row">
  <% item.pimages.each do |pi| %>
      <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 userAvatarStyle-lg ">
        <%= link_to(image_tag(pi.imageurl.thumb400.url, alt:pi.imageurl, class: "imagesStyle"), pi.imageurl.url, class: "imagesStyle", data:{ lightbox: "content"})  if res_img %>
      </div>
  <% end %>
  </div>
  </div>
</div>
<% end %>

app/views/admin_pages/_statuses.html.erb
<div id="status_panel_<%= item.id %>">
  <%= link_to "DESTROY", url_for(controller: 'admin_pages', action: 'delete_queue', id: item.id), method: :put%> |
  <%= link_to "REMOTE", url_for(controller: 'admin_pages', action: 'update_queue_status', id: item.id, status: ConstHelper::STATUS_DELETED), method: :put, remote: true %> |
  <%= link_to "ERROR", url_for(controller: 'admin_pages', action: 'update_queue_status', id: item.id, status: ConstHelper::STATUS_ERROR), method: :put, remote: true %> |
  <%= link_to "HIDDEN", url_for(controller: 'admin_pages', action: 'update_queue_status', id: item.id, status: ConstHelper::STATUS_HIDDEN), method: :put, remote: true %> |
  <%= link_to "EXCEPT", url_for(controller: 'admin_pages', action: 'update_queue_status', id: item.id, status: ConstHelper::STATUS_NOT_PROCESSED), method: :put, remote: true %> |
  <%= link_to "PENDING", url_for(controller: 'admin_pages', action: 'update_queue_status', id: item.id, status: ConstHelper::STATUS_IN_PROCESS), method: :put, remote: true %> |
  <%= link_to "TREATED",  url_for(controller: 'admin_pages', action: 'update_queue_status', id: item.id, status: ConstHelper::STATUS_PROCESSED), method: :put, remote: true %> |

  <% if item.style.status == ConstHelper::BOT_STYLE_IMAGE%>
    <%= link_to "FILTER rob bot", url_for(controller: 'admin_pages', action: 'update_style_status', id: item.id, status: 0), method: :put, remote: true %> |
  <% else %>
    <%= link_to "POST FILTER bot", url_for(controller: 'admin_pages', action: 'update_style_status', id: item.id, status: ConstHelper::BOT_STYLE_IMAGE), method: :put, remote: true %> |
  <% end %>

  <% if item.content.status == ConstHelper::BOT_CONTENT_IMAGE %>
      <%= link_to "Take away content from BOTA", url_for(controller: 'admin_pages', action: 'update_content_status', id: item.id, status: 0), method: :put, remote: true %>
  <% else %>
      <%= link_to "GIVE CONTENT bot", url_for(controller: 'admin_pages', action: 'update_content_status', id: item.id, status: ConstHelper::BOT_CONTENT_IMAGE), method: :put, remote: true %>
  <% end %>

</div>

app/views/admin_pages/images.html.erb
<br>
<%= link_to 'Main', admin_pages_main_path %> |
<%= link_to 'All', url_for(controller: 'admin_pages', action: 'images')%> |
<%= link_to 'All with result', url_for(controller: 'admin_pages', action: 'images', pimage: true)%> |
<%= link_to 'Deleted', url_for(controller: 'admin_pages', action: 'images', status: ConstHelper::STATUS_DELETED)%> |
<%= link_to 'Error', url_for(controller: 'admin_pages', action: 'images', status: ConstHelper::STATUS_ERROR)%> |
<%= link_to 'Hidden', url_for(controller: 'admin_pages', action: 'images', status: ConstHelper::STATUS_HIDDEN)%> |
<%= link_to 'Not processed', url_for(controller: 'admin_pages', action: 'images', status: ConstHelper::STATUS_NOT_PROCESSED)%> |
<%= link_to 'Processed', url_for(controller: 'admin_pages', action: 'images', status: ConstHelper::STATUS_PROCESSED)%> |
<%= link_to 'Processed by bot', url_for(controller: 'admin_pages', action: 'images', status: ConstHelper::STATUS_PROCESSED_BY_BOT)%>
<br>

<div id="posts">
  <% if @items.count > 0 %>
      <%= render partial: 'item_view_4', collection:  @items %>
  <% else %>
      <h3>Your collection is empty</h3>
  <% end %>
</div>

<%= will_paginate @items %>

app/views/admin_pages/images.js.erb
$('#posts').append('<%= escape_javascript render(partial: 'item_view_4', collection:  @items, format: 'html') %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@items) %>');

app/views/admin_pages/main.html.erb
<br>
<br>
<p><%= link_to 'QueueImage', admin_pages_images_path , class: "btn btn-primary btn-large" %><p/>
<p><%= link_to 'Contents', contents_path, class: "btn btn-primary btn-large" %>  <%= link_to 'Styles', styles_path, class: "btn btn-primary btn-large" %><p/>
<br><br>
<p><%= link_to 'Start process', admin_pages_startprocess_path, class: "btn btn-primary btn-large" %><p/>
<br>
<p><%= link_to 'Start bot', admin_pages_startbot_path, class: "btn btn-primary btn-large" %><p/>
<br>
<p><%= link_to 'Unreg workers', admin_pages_unregworkers_path, class: "btn btn-primary btn-large" %><p/>

<br>
<p>Clients: <%= Client.all.count%><p/>
<p>Unprocessed: <%= QueueImage.where(status: 1).count%><p/>
<p>Processed: <%= QueueImage.where(status: 11).count %><p/>

app/views/admin_pages/update_content_status.js.erb
$('#status_panel_<%= @queue_image.id %>').replaceWith('<%= escape_javascript(render  partial: 'statuses', :locals => {item: @queue_image}) %>')

app/views/admin_pages/update_queue_status.js.erb
$('#qi_status_<%= @queue_image.id %>').replaceWith('<div id="qi_status_<%= @queue_image.id %>"><span class="textAboutStyle"><%= get_queue_item_status(@queue_image) %></span>   </div>')

app/views/admin_pages/update_style_status.js.erb
$('#status_panel_<%= @queue_image.id %>').replaceWith('<%= escape_javascript(render  partial: 'statuses', :locals => {item: @queue_image}) %>')

app/views/admin_pages/users.html.erb
<h1>AdminPages#users</h1>
<p>Find me in app/views/admin_pages/users.html.erb</p>