config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :styles

  resources :contents
  get 'admin_pages/main'
  get 'admin_pages/images'
  get 'admin_pages/users'
  get 'admin_pages/startbot'
  get 'admin_pages/startprocess'
  get 'admin_pages/unregworkers'
  get 'admin_pages/update_queue_status'
  match '/admin_pages/update_queue_status', to: 'admin_pages#update_queue_status', via: 'put'
  match '/admin_pages/update_style_status', to: 'admin_pages#update_style_status', via: 'put'
  match '/admin_pages/update_content_status', to: 'admin_pages#update_content_status', via: 'put'
  match '/admin_pages/delete_queue', to: 'admin_pages#delete_queue', via: 'put'

  devise_for :clients, :controllers => { :omniauth_callbacks => "callbacks", :sessions => 'clients/sessions' }
  resources :queue_images
  match '/queue_images/:id/visible', to: 'queue_images#visible', via: 'put'
  match '/queue_images/:id/hidden', to: 'queue_images#hidden', via: 'put'
  match '/queue_images/:id/like', to: 'queue_images#like_image', via: 'put'
  match '/queue_images/:id/unlike', to: 'queue_images#unlike_image', via: 'put'
  get '/queue_images/:id/loaded', to: 'queue_images#loaded'
  post '/queue_images/:id/post_facebook' => 'queue_images#post_facebook', as: :post_facebook_queue_images
  get 'static_pages/lenta', as: 'user_root'
  get '/queue_images/:id/modal' => 'queue_images#show_modal', as: :queue_image_show_modal

  match '/about', to: 'static_pages#about', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/error', to: 'static_pages#error', via: 'get'
  match '/lenta', to: 'static_pages#lenta', via: 'get'
  match '/mixing_level', to: 'static_pages#mixing_level', via: 'get'
  match '/premium', to: 'static_pages#premium', via: 'get'

  resources :blog_posts do
    resources :comments
  end

  resources :comments, only: [:create]

  post '/credits' => 'credits#add', as: :add_credits

  root "static_pages#lenta"
  authenticate :admin do
    mount Resque::Server, :at => "/resque"
  end

end

app/models/queue_image.rb
class QueueImage < ActiveRecord::Base
  has_many :pimages , dependent: :destroy
  belongs_to :client
  belongs_to :content
  belongs_to :style
  has_many :likes, foreign_key: "queue_id", dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  #mount_uploader :content_image, AvatarUploader
  #mount_uploader :style_image, AvatarUploader
  scope :last_n_days, lambda {|d|  where('ftime > ?' , Time.now - d.days)}

  validate :has_credits, on: :create

  @@maximum_per_client = 25


  # I believe you can replace the whole method by distance_of_time_in_words
  def time_ago
    return '' if updated_at.nil?
    t_ago = (Time.now - updated_at)/60


    return 'сейчас' if t_ago < 1
    str = "#{t_ago.to_i} м"
    t_ago = (t_ago/60)
    if t_ago < 1
      return str
    else
      str = "#{t_ago.to_i} ч"
    end
    t_ago = (t_ago/24)
    if t_ago < 1
      return str
    else
      str = "#{t_ago.to_i} д"
    end
    t_ago = (t_ago/30)
    if t_ago < 1
      return str
    else
      str = "#{t_ago.to_i} м"
    end
    t_ago = (t_ago/12)
    if t_ago < 1
      return str
    else
      str = "#{t_ago.to_i} г"
    end
    str
  end

  def result_image
    if pimages.count > 0
      pimages.all.order('created_at DESC').first
    end
  end

  def self.maximum_per_client
    @@maximum_per_client
  end

  def has_credits
    if is_premium
      errors.add(:credits, 'You have not enough credits') unless client.has_credits
    end
  end

  def likers
    likers_array = likes.map { |like| like.client.name }
    likers_array.to_sentence
  end
end

app/controllers/queue_images_controller.rb
class QueueImagesController < ApplicationController
  include WorkerHelper
  include ConstHelper
  before_action :set_queue_image, only: [:show, :edit, :update, :destroy, :visible, :hidden, :like_image, :unlike_image, :post_facebook]
  before_action :authorize_queue_image, only: [:edit, :update, :destroy, :visible, :hidden, :like_image, :unlike_image, :post_facebook]
  after_action :verify_authorized, except: [:show, :tag, :loaded, :show_modal]
  before_action :increment_credit, only: [:post_facebook]
  before_action :not_image_owner, only: [:like_image, :unlike_image]

  def pundit_user
    current_client
  end

  # GET /queue_images
  # GET /queue_images.json
  def index
    #@items= current_client.queue_images.all.order('created_at DESC')
    #@items= policy_scope(current_client.queue_images).order('created_at DESC').paginate(:page => params[:page], :per_page => 6)
    authorize QueueImage
    @items = policy_scope(current_client.queue_images).order('created_at DESC').paginate(:page => params[:page], :per_page => 6)
    #@items= QueueImage.where("status > 9").order('ftime DESC').paginate(:page => params[:page], :per_page => 6)
  end

  # GET /queue_images/1
  # GET /queue_images/1.json
  def show
    @comments = @queue_image.comments
    @comment = @queue_image.comments.new
  end

  # GET /queue_images/new
  def new
    @image_count = current_client.queue_images.count
    @maximum_reached = current_client.reached_maximum?
    @my_queue_images = current_client.queue_images
    @queue_image = QueueImage.new
    @styles = Style.where(status: ConstHelper::GALLERY_STYLE_IMAGE).order('use_counter desc')
    @tags = @styles.tag_counts_on(:tags)
    @active = Style.find(params[:style]) if params[:style]
    @mixing_level = params[:mixing_level]
    @is_premium = params[:is_premium]
    if @my_queue_images
      @my_styles = @my_queue_images.map { |qi| qi.style }
      @my_styles.uniq!
      @my_styles.compact!
      @my_pictures = @my_queue_images.map { |qi| qi.content }
      @my_pictures.uniq!
      @my_pictures.compact!
    end
    authorize @queue_image
    respond_to do |format|
      format.html { render :new}
      format.js
    end
  end

  # GET /queue_images/1/edit
  def edit

  end

  # POST /queue_images
  # POST /queue_images.json
  def create
    authorize QueueImage
    unless valid_queue_image_params
      redirect_to new_queue_image_path
      return
    end

    max_reached = current_client.reached_maximum?
    qi_service = QueueImageService.new queue_image_params, current_client
    save_status = qi_service.create_queue

    if save_status && max_reached
      current_client.delete_older_image
    end

    respond_to do |format|
      if save_status
        start_workers()
        current_client.decrement! :credits, Client.credits_for_image if params[:queue_image][:is_premium] == "true"
        format.html { redirect_to queue_images_path, notice: 'Image was successfully added to the queue for processing. Low-resolution images takes about 10 seconds to process, and high-resolution images takes 20 seconds to 4 minutes depending on the image size' }
        format.json { render :show, status: :created, location: @queue_image }
      else
        format.html { redirect_to new_queue_image_path, alert: qi_service.errors.to_sentence }
        format.json { render json: @queue_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /queue_images/1
  # PATCH/PUT /queue_images/1.json
  def update
    respond_to do |format|
      if @queue_image.update(queue_image_params)
        format.html { redirect_to @queue_image, notice: 'Queue image was successfully updated.' }
        format.json { render :show, status: :ok, location: @queue_image }
      else
        format.html { render :edit }
        format.json { render json: @queue_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queue_images/1
  # DELETE /queue_images/1.json
  def destroy
    content = @queue_image.content
    puts content.queue_images.count
    if content.queue_images.count > 1
      @queue_image.destroy
    else
      content.destroy
    end
    respond_to do |format|
      format.html { redirect_to queue_images_url, notice: 'Images removed.' }
      format.json { head :no_content }
    end
  end

  def visible
    @queue_image.update(status: STATUS_PROCESSED)
    respond_to do |format|
      format.html { redirect_to queue_images_url, notice: 'Images become publicly visible.' }
      format.json { head :no_content }
    end
  end

  def hidden
    @queue_image.update(status: STATUS_HIDDEN)
    respond_to do |format|
      format.html { redirect_to queue_images_url, notice: 'The images are hidden.' }
      format.json { head :no_content }
    end
  end

  def like_image
    Like.transaction do
      today_likes = current_client.likes.where created_at: (Time.now - 24.hours)..Time.now
      current_client.increment!(:credits, 1) if today_likes.count < 3
      Like.create(queue_id: @queue_image.id, client_id: current_client.id)
      @queue_image.increment! :likes_count, 1
      @queue_image.client.increment! :credits, 1
    end
    respond_to do |format|
      format.html { redirect_to queue_images_url}
      format.js
    end
  end

  def unlike_image
    Like.transaction do
      today_likes = current_client.likes.where created_at: (Time.now - 24.hours)..Time.now
      current_client.decrement!(:credits, 1) if today_likes.count > 0 && today_likes.count < 4
      Like.where("client_id = #{current_client.id} and queue_id = #{@queue_image.id}").destroy_all
      @queue_image.decrement! :likes_count, 1
      @queue_image.client.decrement! :credits, 1
    end
    respond_to do |format|
      format.html { redirect_to queue_images_url}
      format.js
    end
  end

  def loaded
    @queue_image = QueueImage.find(params[:id])
    respond_to do |format|
      if @queue_image.result_image
        format.js
      else
        format.js { render 'loaded', status: 501 }
      end
    end
  end

  def post_facebook
    @graph = Koala::Facebook::API.new(current_client.token)
    photo = @queue_image.result_image.imageurl.url
    if photo
      @graph.put_picture "#{photo}", nil, { caption: params[:message] }
    end

    respond_to do |format|
      format.js
    end
  end

  def show_modal
    @queue_image = QueueImage.find(params[:id])
    @comments = @queue_image.comments
    @comment = @queue_image.comments.new

    respond_to do |format|
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_queue_image
    @queue_image = QueueImage.find(params[:id])
  end

  def authorize_queue_image
    authorize @queue_image
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def queue_image_params
    params.require(:queue_image).permit(:content_id, :content_image, :mixing_level, :is_premium, :style_image, :style_id, :init_str, :status, :result, :init, :end_status)
  end

  def valid_queue_image_params
    if params[:queue_image][:content_image].nil? && params[:queue_image][:content_id].nil?
      flash[:alert] = "Please add or select an image for rendering"
      return false
    end
    true
  end

  def decrement_credit
    current_client.decrement! :credits, 1
  end

  def increment_credit
    current_client.increment! :credits, 1
  end

  def not_image_owner
    if @queue_image.client == current_client
      redirect_to queue_images_url
    end
  end
end

app/helpers/queue_images_helper.rb
module QueueImagesHelper
end

app/views/queue_images/_form.html.erb
<h1></h1>
<div class="container">
  <div class="row">
    <div class="col-lg-offset-4 col-lg-4 col-md-12 col-sm-12 col-xs-12">

    <%= form_for(@queue_image) do |f| %>
      <% if @queue_image.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@queue_image.errors.count, "error") %> Wrong data:</h2>

          <ul>
          <% @queue_image.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <div class="field">
        <%= f.label "rendered image:" %><br>
        <%= f.file_field :content_image %>
      </div>
      <div class="field hidden">
         <%= f.label "Upload a file:" %><br>
         <%= f.check_box :from_file, {checked: true} %>
      </div>
      <div class="field">
        <%= f.label "Library:"%><br>
        <%= f.file_field :style_image %>
      </div>

      <div class="actions">
        <%= f.submit "Add to processing", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/queue_images/_item.html.erb
<% debug = true %>
<%res_img = item_view_1.result_image %>

<li id="<%= item.id %>">


  <% if item.status > 1 %>
      <div class="row successMessage">
  <% else %>
      <div class="row">
  <% end %>


    <div class="col-md-1">
      <%= link_to(image_tag(item.content_image.thumb.url, alt:item.content_image, class: "productImage"), item.content_image.url, data:{ lightbox: "content"}) %>
    </div>

    <div class="col-md-1">
      <%= link_to(image_tag(item.style_image.thumb.url, alt:item.style_image, class: "productImage"), item.style_image.url, data:{ lightbox: "content"}) %>
    </div>


    <div class="col-md-1">
      <%= link_to(image_tag(res_img.imageurl.thumb.url, alt:res_img.imageurl, class: "productImage"), res_img.imageurl.url, data:{ lightbox: "content"})  if res_img %>
    </div>

    <div class="col-md-3 hidden-phone">
      <% if false %>
      <span class="user">
       <%= link_to "share", item, method: :delete,
                   data: { confirm: "You sure?" } %>
      </span>
       <% end %>


      <span class="content"><p>Добавлено: <%= (item.created_at+10800).strftime("%d.%m.%Y %H:%M:%S")%></p> </span>


      <span class="timestamp">
        <% if item.status < 0 %>
            <p> Error rendering </p>
        <% elsif item.status == 0 %>
            <p> Pending </p>
        <% elsif item.status == 1 %>
            <p> Rendered at (<%= item.pimages.count * 10 %>% </p>
        <% elsif item.status > 1 %>
            <p> Rendered for <%= item.ptime.strftime("%H:%M:%S")if !item.ptime.nil? %> </p>
        <% end %>
      </span>

      <span class="user">
        <p> </p>
        <% if debug && item.status != 1 %>
        <%= link_to "remove", item, method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
         <% end %>
      </span>

    </div>


  </div>

</li>

app/views/queue_images/_item_view_1.html.erb
<% item = item_view_1 %>
<div class="col-xs-12 col-sm-6 col-md-4">
  <div class="queue-image" data-queue-image-id="<%= item.id %>">
    <div class="images-wrapper">
      <%= link_to queue_image_path(item), class: 'queue-image-link' do %>
        <% if item.content.image && item.content.image.thumb400.file.exists? %>
          <%= image_tag(item.content.image.thumb400.url, class: 'original') %>
        <% elsif item.content.image %>
          <%= image_tag(item.content.image.thumb200.url, class: 'original') %>
        <% end %>
        <%= image_tag(item.result_image.imageurl.thumb400.url, class: 'styled') if item.result_image %>
      <% end %>
    </div>
    <div class="queue-image-ifc">
    <% if current_client %>
      <%= link_to 'Use Style', new_queue_image_path(style: item.style.id), class: "use-style" %>
    <% else %>
      <%= link_to 'Use Style', new_client_session_path %>
    <% end %>
    <%= link_to 'Comments', queue_image_path(item) %>
    <%= render partial: 'queue_images/like_link', collection: [item] %>
    </div>
  </div>
</div>

app/views/queue_images/_item_view_3.html.erb
<% debug = false %>

<% item = item_view_3 %>
<% res_img = item.result_image %>

<div class="row styleRow2-lg queue-image-item" data-item-id="<%= item.id %>" <%= 'data-loading' unless item.result_image %>>
  <div class="visible-lg  col-lg-2 col-lg-offset-2 userAvatarStyle-lg" >
    <%= image_tag(item.content.image.thumb200.url, class: "imagesStyle roundImageStyle") %>
  </div>
  <div class="visible-lg  col-lg-2 userAvatarStyle-lg">
    <%= link_to(image_tag(item.style.image.thumb200.url, alt:item.style.image, class: "imagesStyle roundImageStyle"), new_queue_image_path(style: item.style.id, is_premium: item.is_premium, mixing_level: item.mixing_level), class: "imagesStyle", data:{ lightbox: "content"}) %>
  </div>

  <div class="hidden-lg col-md-2 col-sm-3 col-xs-3 col-md-offset-2 userAvatarStyle-lg" >
    <%= image_tag(item.content.image.thumb200.url, class: "imagesStyle roundImageStyle")%>
  </div>
  <div class="hidden-lg col-md-2 col-sm-3 col-xs-3 userAvatarStyle-lg">
    <%= link_to(image_tag(item.style.image.thumb200.url, alt:item.style.image, class: "imagesStyle roundImageStyle"), new_queue_image_path(style: item.style.id, is_premium: item.is_premium, mixing_level: item.mixing_level), class: "imagesStyle") %>
  </div>

  <div class="col-lg-2 col-md-2 col-sm-3 col-xs-3 userAvatarStyle-lg">
    <% if !res_img.nil? %>
        <div class="visible-lg" >
          <%= link_to(image_tag(res_img.imageurl.thumb400.url, alt:res_img.imageurl, class: "imagesStyle roundImageStyle"), res_img.imageurl.url, class: "imagesStyle", data:{ lightbox: "content"})  if res_img %>
        </div>
        <div class="hidden-lg" >
          <%= link_to(image_tag(res_img.imageurl.thumb400.url, alt:res_img.imageurl, class: "imagesStyle roundImageStyle"), res_img.imageurl.url, class: "imagesStyle")  if res_img %>
        </div>
    <% else %>
      <%= image_tag("/loading_2.png", class: "imagesStyle") %>
    <% end %>
  </div>

  <div class=" col-lg-2 col-md-2 col-sm-3 col-xs-3 ">
    <% if res_img && current_client.provider == 'facebook' %>
      <%= link_to "#", class: 'post_facebook', data: { toggle: "modal", target: "#facebook-post-modal", id: item.id } do %>
        <%= image_tag '/fb.jpg' %>Share on Facebook
      <% end %>
    <% end %>
  	<span class="textAboutStyle">mixing_level: <%= item.mixing_level %></span><br>
	  <span class="textAboutStyle">high_resolution: <%= item.is_premium %></span><br>
    <span class="textAboutStyle"><%# (item.created_at+10800).strftime("%d.%m.%Y %H:%M:%S")%></span><br>
    <span class="textAboutStyle"><%= get_queue_item_status(item) %></span><br>
    <span class="textAboutStyle">
      <% if policy(item).destroy? %>
        <%= link_to "Remove", item, method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
      <% end %><br>
      <% if policy(item).hidden? %>
        <%= link_to "Hide", "/queue_images/#{item.id}/hidden", method: :put, data: { confirm: "It is good to share with the world. Are you sure you want to hide?" } %>
      <% end %>
      <% if policy(item).visible? %>
        <%= link_to "Show", "/queue_images/#{item.id}/visible", method: :put %>
      <% end %>
    </span>
    <% if item.status == ConstHelper::STATUS_IN_PROCESS %>
      <div class="progressBar">
        <span style="width: <%= item.progress.to_i%>%"></span>
      </div>
    <% end %>
  </div>
</div>

app/views/queue_images/_like.html.erb
<% classes = "like_panel_#{item.id}" %>
<% classes << ' liked' unless policy(item).like_image? || !client_signed_in? %>

<% if client_signed_in? %>
  <% if item.client != current_client %>
    <% if policy(item).like_image? %>
      <%= link_to("/queue_images/#{item.id}/like", class: classes, method: :put, remote: true) do %>
        <%= item.likes_count %>
      <% end %>
    <% else %>
      <%= link_to("/queue_images/#{item.id}/unlike", class: classes, method: :put, remote: true) do %>
        <%= item.likes_count %>
      <% end %>
    <% end %>
  <% else %>
    <div class="<%= classes %>">
      <%= item.likes_count %>
    </div>
  <% end %>
<% else %>
  <%= link_to(new_client_registration_path, class: classes, method: :put, remote: true) do %>
    <%= item.likes_count %>
  <% end %>
<% end %>

app/views/queue_images/_modal.html.erb
<% debug = false %>

<div class="row modal-queue-image-view">
  <div class="col-md-8">
    <div class="overflow ta-center">
      <button type="button" class="btn btn-default visible-xs modal-close" data-dismiss="modal">Close</button>
      <%= link_to 'Open in a new window', queue_image_path(queue_image) %>
    </div>
	<div class="sharethis-inline-share-buttons"></div>
    <div class="row modal-pics">
      <div class="col-sm-4 col-lg-4 styleContentImage1-lg ">
        <div class="row">
          <div class="col-xs-12" >
            <%= image_tag(queue_image.content.image.thumb200.url, class: "imagesStyle roundImageStyle") %>
          </div>
          <div class="col-xs-12">
            <%= link_to(image_tag(queue_image.style.image.thumb200.url, alt:queue_image.style.image, class: "imagesStyle roundImageStyle"), new_queue_image_path(style: queue_image.style.id, is_premium: queue_image.is_premium, mixing_level: queue_image.mixing_level), class: "imagesStyle", data:{ lightbox: "content"}) %>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-7 col-lg-7 imageBlock400-lg">
        <%= link_to(image_tag(queue_image.result_image.imageurl.thumb400.url, alt: queue_image.result_image.imageurl, class: "imagesStyle roundImageStyle"), queue_image.result_image.imageurl.url, class: "imagesStyle", data:{ lightbox: "content"})  if queue_image.result_image %>
      </div>
    </div>

  </div>
  <div class="col-md-4">
    <div class="queue-image-data">
      <div class="user-info">
        <%= image_tag(queue_image.client.remote_avatar || queue_image.client.avatar, class: "userAvatarImage-lg") if queue_image.client.present? %>
        <span class="textUserStyle-lg">
          <%= truncate(queue_image.client.name, length: 25)  if queue_image.client.present? %>
        </span>
      </div>
      <% if debug %>
        <span class="user">
            <%= link_to "remove", queue_image, method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
        </span>
      <% end %>
      <div class="modal-like" data-toggle="tooltip" data-placement="bottom" title="<%= queue_image.likers %>" >
        <%= render(partial: 'queue_images/like', :locals => {item: queue_image}) %>
      </div>
    </div>
    <div class="image-info">
      Mixing level: <%= queue_image.mixing_level %>, Image Resolution: <%= queue_image.is_premium ? 'High' : 'Low' %>
    </div>
    
    <div id="comments">
      <%= render partial: 'comments/comment', collection: @comments %>
    </div>
    <% if current_client %>
      <%= render partial: 'comments/form', locals: { comment: @comment, remote: true } %>
    <% else %>
      <%= link_to "Sign In", new_client_session_path %>
      or
      <%= link_to "Register", new_client_registration_path %>
      to leave a comment
    <% end %>
	<div id="ad">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<!-- photopaintus -->
	<ins class="adsbygoogle"
			 style="display:block"
			 data-ad-client="ca-pub-8024423611464128"
			 data-ad-slot="8605271892"
			 data-ad-format="auto"></ins>
		 <script>
(adsbygoogle = window.adsbygoogle || []).push({});
	 </script>
	 </div>
  </div>
</div>

app/views/queue_images/edit.html.erb
<h3>Editing</h3>

<%= render 'form' %>


<%= link_to 'image queues', queue_images_path %>

app/views/queue_images/index.html.erb
<div id="posts">
  <% if @items.count > 0 %>
      <%= render partial: 'item_view_3', collection: @items %>
  <% else %>
      <h3>Your collection is empty</h3>
  <% end %>
</div>

<div id="facebook-post-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="overflow visible-xs">
          <%= button_tag "Close", class: 'btn btn-link modal-close', data: { dismiss: 'modal' } %>
        </div>
        <%= form_tag '/queue_images/:id/post_facebook', method: :post, remote: true, authenticity_token: true do %>
          <%= text_area_tag :message, nil, placeholder: "Optional message", class: 'form-control' %>
          <%= button_tag "Post", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= will_paginate @items %>

app/views/queue_images/index.js.erb
$('#posts').append('<%= escape_javascript render(partial: 'item_view_3', collection:  @items, format: 'html') %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@items) %>');

app/views/queue_images/like_image.js.erb
$('.like_panel_<%= @queue_image.id %>').replaceWith('<%= escape_javascript(render  partial: 'like', :locals => {item: @queue_image}) %>');
$('.like-block[data-item-id="<%= @queue_image.id %>"').html('<%= @queue_image.likes_count %>').addClass('active');
$('.like-link[data-item-id="<%= @queue_image.id %>"').replaceWith("<%= escape_javascript(render partial: 'like_link', collection: [@queue_image]) %>");
console.log("<%= escape_javascript(render partial: 'like_link', collection: @queue_image) %>");
$(".credits").html("<%= current_client.credits %>");

app/views/queue_images/loaded.js.erb
<% if @queue_image.result_image %>
  $(".queue-image-item[data-item-id='<%= @queue_image.id %>']").replaceWith("<%= escape_javascript(render partial: 'item_view_3', collection: [@queue_image] ) %>");
<% end %>

app/views/queue_images/new.js.erb
$('#view_style').replaceWith('<%= escape_javascript(render  partial: 'view_style', :locals => {view_style: @view_style, queue_image: @queue_image}) %>');
bindTagsFunctionality();

app/views/queue_images/post_facebook.js.erb
$("#facebook-post-modal").modal("hide");
$('#facebook-post-modal button').html("Post");
$('#facebook-post-modal button').prop('disabled', false);
$("[data-item-id=<%= @queue_image.id %>]").find(".post_facebook").replaceWith("Posted<br>");
$(".credits").html("<%= current_client.credits %>");

app/views/queue_images/unlike_image.js.erb
$('.like_panel_<%= @queue_image.id %>').replaceWith('<%= escape_javascript(render  partial: 'like', :locals => {item: @queue_image}) %>');
$('.like-block[data-item-id="<%= @queue_image.id %>"').html('<%= @queue_image.likes_count %>').removeClass('active');
$('.like-link[data-item-id="<%= @queue_image.id %>"').replaceWith("<%= escape_javascript(render partial: 'like_link', collection: [@queue_image]) %>");
console.log("<%= escape_javascript(render partial: 'like_link', collection: @queue_image) %>");
$(".credits").html("<%= current_client.credits %>");