config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :styles

  resources :contents
  get 'admin_pages/main'
  get 'admin_pages/images'
  get 'admin_pages/users'
  get 'admin_pages/startbot'
  get 'admin_pages/startprocess'
  get 'admin_pages/unregworkers'
  get 'admin_pages/update_queue_status'
  match '/admin_pages/update_queue_status', to: 'admin_pages#update_queue_status', via: 'put'
  match '/admin_pages/update_style_status', to: 'admin_pages#update_style_status', via: 'put'
  match '/admin_pages/update_content_status', to: 'admin_pages#update_content_status', via: 'put'
  match '/admin_pages/delete_queue', to: 'admin_pages#delete_queue', via: 'put'

  devise_for :clients, :controllers => { :omniauth_callbacks => "callbacks", :sessions => 'clients/sessions' }
  resources :queue_images
  match '/queue_images/:id/visible', to: 'queue_images#visible', via: 'put'
  match '/queue_images/:id/hidden', to: 'queue_images#hidden', via: 'put'
  match '/queue_images/:id/like', to: 'queue_images#like_image', via: 'put'
  match '/queue_images/:id/unlike', to: 'queue_images#unlike_image', via: 'put'
  get '/queue_images/:id/loaded', to: 'queue_images#loaded'
  post '/queue_images/:id/post_facebook' => 'queue_images#post_facebook', as: :post_facebook_queue_images
  get 'static_pages/lenta', as: 'user_root'
  get '/queue_images/:id/modal' => 'queue_images#show_modal', as: :queue_image_show_modal

  match '/about', to: 'static_pages#about', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/error', to: 'static_pages#error', via: 'get'
  match '/lenta', to: 'static_pages#lenta', via: 'get'
  match '/mixing_level', to: 'static_pages#mixing_level', via: 'get'
  match '/premium', to: 'static_pages#premium', via: 'get'

  resources :blog_posts do
    resources :comments
  end

  resources :comments, only: [:create]

  post '/credits' => 'credits#add', as: :add_credits

  root "static_pages#lenta"
  authenticate :admin do
    mount Resque::Server, :at => "/resque"
  end

end

app/views/layouts/_footer.html.erb
<div class="col-xs-12">
  <footer class="footer">
    <small>
      PhotoPaint
    </small>
    <nav>
    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb

<div class="navbar navbar-fixed-top navbar-inverse  visible-lg" role="navigation">
  <div class="container headerStyle-lg">
      <div id="logo-lg">
        <%= link_to(image_tag('/logo1.png', class: "imagesStyle"), root_path )%>
      </div>

      <ul class="nav nav-pills pull-right">
        <% if client_signed_in? && current_client.admin? %>
            <li><%= link_to "Admin", admin_pages_main_path %></li>
        <% end %>
        <% if client_signed_in? %>

          <li><%= link_to "Create Images", new_queue_image_path, class: "btn btn-primary" %></li>

          <li>
            <%= link_to "My Collections",    queue_images_path %>
            <div data-tip="2" class="tip">
              -1 credit for each high resolution image. Earn credits by liking other images (3 per day) or just visiting the website (1 per day)
              <a class="btn">OK</a>
            </div>
          </li>
        <% end %>
        <li><%= link_to "Latest Arts", lenta_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Blog", blog_posts_path %></li>
        <% if client_signed_in? %>
          <li>
            <%= link_to "Log Out",  destroy_client_session_path, :method => :delete %>
          </li>
          <li class="avatar">
            <%= image_tag current_client.remote_avatar || current_client.avatar %>
          </li>
          <div class="credits visible-lg">
            <%= current_client.credits %>
            <div data-tip="1" class="tip">
              Your credits amount
              <a class="btn">OK</a>
            </div>
          </div>
        <% else %>
          <li><%= link_to 'Sign In', new_client_session_path %></li>
        <% end %>
      </ul>

    <!-- /.nav-collapse -->
  </div>
  <!-- /.container -->
</div>


<div class="navbar navbar-fixed-top navbar-inverse  hidden-lg" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle navButtonStyle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if client_signed_in? %>
        <div class="credits hidden-lg">
          <%= current_client.credits %>
          <div data-tip="1" class="tip">
            Your credits amount
            <a class="btn">OK</a>
          </div>
        </div>
      <% end %>

      <div id="logo-xs">
        <%= link_to(image_tag('/logo1.png', class: "imagesStyle"), root_path) %>
      </div>
    </div>

    <div class="navbar-collapse collapse" aria-expanded="false">
      <ul class="nav navbar-nav">
        <% if client_signed_in? && current_client.admin? %>
            <li><%= link_to "ADMIN", admin_pages_main_path %></li>
        <% end %>
        <% if client_signed_in? %>
            <li><%= link_to "Create Images", new_queue_image_path %></li>
            <li style="border-top: 1px solid #000000;box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1);" ><%= link_to "My Collections",    queue_images_path %></li>
        <% end %>
        <li ><%= link_to "Latest Arts",  lenta_path %></li>
        <li><%= link_to "About",    about_path %></li>
        <li><%= link_to "Blog", blog_posts_path %></li>
        <% if client_signed_in? %>
            <li><%= link_to "Log Out",  destroy_client_session_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to 'Sign In', new_client_session_path %></li>
        <% end %>
      </ul>
    </div>



    <!-- /.nav-collapse -->
  </div>
  <!-- /.container -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-8024423611464128",
    enable_page_level_ads: true
  });
</script>
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58d1ecd666585d00122d5a00&product=inline-share-buttons"></script>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/shim' %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% if notice %>
        <label class="successMessage"><%= notice %></label>
      <% end %>
      <% if alert %>
          <label class="errorMessage"><%= alert %></label>
      <% end %>
      <% flash.each do |key, value| %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application_1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoPaint</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>